[tool.poetry]
name = "shellphish-qemu"
version = "0.1.0"
description = ""
authors = ["2over12 <ian.smith@trailofbits.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
